apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxterm-site
  namespace: xxterm
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx    # 兼容旧版 Ingress Controller 写法
spec:
  rules:
    - host: xxterm.haohanxingchen.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xxterm-site
                port:
                  number: 80
